name: Build docker image for future downloads

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          platforms: linux/arm/v8
          push: false
          tags: smart-mirror-backend
          outputs: type=docker,dest=./smart-mirror-backend.image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          platforms: linux/arm/v8
          push: false
          tags: smart-mirror-frontend
          outputs: type=docker,dest=./smart-mirror-frontend.image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-mirror-backend
          path: ./smart-mirror-backend.image.tar
          if-no-files-found: error

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-mirror-frontend
          path: ./smart-mirror-frontend.image.tar
          if-no-files-found: error
