name: Validate PRs

on:
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Typecheck
        run: npm run typecheck
        working-directory: ./frontend

      - name: ESLint
        run: npm run lint
        working-directory: ./frontend

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Go dependencies
        run: go mod download
        working-directory: ./server

      - name: Run go vet
        run: go vet ./...
        working-directory: ./server

      - name: Run go test
        run: go test ./...
        working-directory: ./server

      - name: Check Go formatting
        run: gofmt -l .
        working-directory: ./server
