name: Validate PRs

on:
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Typecheck
        run: npm run typecheck
        working-directory: ./frontend